//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eCommerceEntities : DbContext
    {
        public eCommerceEntities()
            : base("name=eCommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<ARCodeType> ARCodeTypes { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<Invoice_Trans> Invoice_Trans { get; set; }
        public virtual DbSet<Payment_Types> Payment_Types { get; set; }
        public virtual DbSet<RemittanceDetail> RemittanceDetails { get; set; }
        public virtual DbSet<SetNumber> SetNumbers { get; set; }
        public virtual DbSet<SetReversal> SetReversals { get; set; }
        public virtual DbSet<SlateDetailGLNumber> SlateDetailGLNumbers { get; set; }
        public virtual DbSet<SlateDetail> SlateDetails { get; set; }
        public virtual DbSet<SummerGLChanx> SummerGLChanges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<Trans_Status_Types> Trans_Status_Types { get; set; }
        public virtual DbSet<WEB_Address> WEB_Address { get; set; }
        public virtual DbSet<WEB_ChargeType> WEB_ChargeType { get; set; }
        public virtual DbSet<WEB_ControlEvaluationTypes> WEB_ControlEvaluationTypes { get; set; }
        public virtual DbSet<WEB_CouponCodeTypes> WEB_CouponCodeTypes { get; set; }
        public virtual DbSet<WEB_Customer> WEB_Customer { get; set; }
        public virtual DbSet<WEB_Invoice_Items> WEB_Invoice_Items { get; set; }
        public virtual DbSet<WEB_Invoices> WEB_Invoices { get; set; }
        public virtual DbSet<WEB_InvoiceType> WEB_InvoiceType { get; set; }
        public virtual DbSet<WEB_ItemCouponCodes> WEB_ItemCouponCodes { get; set; }
        public virtual DbSet<WEB_ItemType> WEB_ItemType { get; set; }
        public virtual DbSet<WEB_ItemType_CreditGLs> WEB_ItemType_CreditGLs { get; set; }
        public virtual DbSet<WEB_Payments> WEB_Payments { get; set; }
        public virtual DbSet<WebTeamAdministrator> WebTeamAdministrators { get; set; }
        public virtual DbSet<WEB_CustomerUpdate> WEB_CustomerUpdate { get; set; }
        public virtual DbSet<WEB_GLChanges> WEB_GLChanges { get; set; }
        public virtual DbSet<WEB_Invoices_Archive> WEB_Invoices_Archive { get; set; }
        public virtual DbSet<Web_InvoiceSupervisors> Web_InvoiceSupervisors { get; set; }
        public virtual DbSet<WEB_ItemTaxes> WEB_ItemTaxes { get; set; }
        public virtual DbSet<WEB_PhoneTypes> WEB_PhoneTypes { get; set; }
        public virtual DbSet<ActiveGLAccounts_v> ActiveGLAccounts_v { get; set; }
        public virtual DbSet<Invoice_Totals_V> Invoice_Totals_V { get; set; }
        public virtual DbSet<Invoice_Trans_Amounts_V> Invoice_Trans_Amounts_V { get; set; }
        public virtual DbSet<Items_Available_V> Items_Available_V { get; set; }
        public virtual DbSet<WEB_ItemTaxes_V> WEB_ItemTaxes_V { get; set; }
    }
}
