//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Trans_Amounts_V
    {
        public int ID { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<int> Set_Number { get; set; }
        public Nullable<int> Item_Type { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
