//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Trans
    {
        public int ID { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<int> Set_Number { get; set; }
        public Nullable<int> Item_Type { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<System.DateTime> Date_Submitted { get; set; }
        public Nullable<int> Transaction_Status { get; set; }
        public string Status_User { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public Nullable<System.DateTime> Date_Processed { get; set; }
        public string Coupon_Code { get; set; }
    }
}
