//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemittanceDetail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DataDate { get; set; }
        public Nullable<int> Completed { get; set; }
        public string RecordIndicator { get; set; }
        public string TransactionConfirmationID { get; set; }
        public string BillerProductCode { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> ConvenienceFee { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentEffectiveDate { get; set; }
        public string InitiationDate { get; set; }
        public string PaymentType { get; set; }
        public string PaymentAuthorization { get; set; }
        public string PaymentStatus { get; set; }
        public string ACHReturnCode { get; set; }
        public string ReasonDescription { get; set; }
        public string ReturnDate { get; set; }
        public string AccessMethod { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string ZipCode5 { get; set; }
        public string ZipCode4 { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> TransactionKey { get; set; }
    }
}
