//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetNumber()
        {
            this.SlateDetails = new HashSet<SlateDetail>();
        }
    
        public int Set_Number { get; set; }
        public Nullable<int> Invoice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlateDetail> SlateDetails { get; set; }
        public virtual WEB_Invoices WEB_Invoices { get; set; }
    }
}
