//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlateDetail
    {
        public int ID { get; set; }
        public System.DateTime date { get; set; }
        public string paymentDescription { get; set; }
        public double netAmount { get; set; }
        public double fee { get; set; }
        public Nullable<int> revenueGLAccountID { get; set; }
        public Nullable<int> feesGLAccountID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string action { get; set; }
        public string whitworthID { get; set; }
        public Nullable<int> invoiceID { get; set; }
        public Nullable<int> setNumberID { get; set; }
        public Nullable<System.DateTime> dateProcessed { get; set; }
    
        public virtual SetNumber SetNumber { get; set; }
        public virtual SlateDetailGLNumber SlateDetailGLNumber { get; set; }
        public virtual SlateDetailGLNumber SlateDetailGLNumber1 { get; set; }
        public virtual WEB_Invoices WEB_Invoices { get; set; }
    }
}
