//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ItemTaxes
    {
        public int ItemType { get; set; }
        public int TaxType { get; set; }
        public string DebitGL { get; set; }
        public string CreditGL { get; set; }
    }
}
