//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_ItemType()
        {
            this.WEB_ItemType_CreditGLs = new HashSet<WEB_ItemType_CreditGLs>();
        }
    
        public int ID { get; set; }
        public int InvoiceType { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<int> ChargeType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Item_Amt { get; set; }
        public string Item_GL_Debit { get; set; }
        public string Control_Name { get; set; }
        public Nullable<int> ControlEvaluationType { get; set; }
        public string Item_AR_Code { get; set; }
        public string Item_Account_Type { get; set; }
        public Nullable<int> ShowOnBackend { get; set; }
        public Nullable<int> AmtVariable { get; set; }
    
        public virtual WEB_InvoiceType WEB_InvoiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_ItemType_CreditGLs> WEB_ItemType_CreditGLs { get; set; }
    }
}
