//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_CustomerUpdate
    {
        public Nullable<int> Customer_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string PREFIX { get; set; }
        public string FULL_NAME { get; set; }
        public string ADDR_Id { get; set; }
        public string Email_Addr { get; set; }
        public string Phone_Number { get; set; }
        public string Phone_Ext { get; set; }
        public string Phone_Type { get; set; }
        public int UpdateID { get; set; }
    }
}
