//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Payments
    {
        public int ID { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<int> Set_Number { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Type { get; set; }
        public string Confirmation_Number { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
        public string Payment_Processed { get; set; }
        public string Cancel_Conf_Number { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string Cancel_Processed { get; set; }
        public Nullable<System.DateTime> Data_Date { get; set; }
    
        public virtual WEB_Invoices WEB_Invoices { get; set; }
    }
}
