//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ItemTaxes_V
    {
        public int ItemType { get; set; }
        public Nullable<decimal> SalesTaxRate { get; set; }
        public string SalesDebitGL { get; set; }
        public string SalesCreditGL { get; set; }
        public Nullable<decimal> BOGoodsTaxRate { get; set; }
        public string BOGoodsDebitGL { get; set; }
        public string BOGoodsCreditGL { get; set; }
        public Nullable<decimal> BOServicesTaxRate { get; set; }
        public string BOServicesDebitGL { get; set; }
        public string BOServicesCreditGL { get; set; }
    }
}
