//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_Customer()
        {
            this.WEB_Invoices = new HashSet<WEB_Invoices>();
        }
    
        public int Customer_ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string PREFIX { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<int> ADDR_Id { get; set; }
        public string Email_Addr { get; set; }
        public string Phone_Number { get; set; }
        public string Phone_Ext { get; set; }
        public string Phone_Type { get; set; }
        public string Whit_ID { get; set; }
        public Nullable<int> Refund_ID { get; set; }
    
        public virtual WEB_Address WEB_Address { get; set; }
        public virtual WEB_Customer WEB_Customer1 { get; set; }
        public virtual WEB_Customer WEB_Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_Invoices> WEB_Invoices { get; set; }
    }
}
