//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_GLChanges
    {
        public int ID { get; set; }
        public Nullable<double> Item_Amt { get; set; }
        public string Item_Action { get; set; }
        public string Item_GL { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<System.DateTime> Date_Submitted { get; set; }
        public Nullable<int> Processed { get; set; }
        public Nullable<System.DateTime> Date_Processed { get; set; }
    }
}
