//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_CouponCodeTypes
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string EffectType { get; set; }
        public Nullable<double> EffectAmount { get; set; }
        public Nullable<int> MaxUse { get; set; }
        public Nullable<int> RequireWhitworthID { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
