//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_Invoices()
        {
            this.SlateDetails = new HashSet<SlateDetail>();
            this.WEB_Invoice_Items = new HashSet<WEB_Invoice_Items>();
            this.WEB_Payments = new HashSet<WEB_Payments>();
            this.SetNumbers = new HashSet<SetNumber>();
        }
    
        public int Inv_NO { get; set; }
        public int Inv_Customer_ID { get; set; }
        public Nullable<int> Inv_TYPE { get; set; }
        public System.DateTime Inv_DATE { get; set; }
        public Nullable<System.DateTime> Inv_Completed { get; set; }
        public Nullable<System.DateTime> Inv_Final_Modify { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlateDetail> SlateDetails { get; set; }
        public virtual WEB_Customer WEB_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_Invoice_Items> WEB_Invoice_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_Payments> WEB_Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetNumber> SetNumbers { get; set; }
    }
}
