//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_Address()
        {
            this.WEB_Customer = new HashSet<WEB_Customer>();
        }
    
        public int ADDR_ID { get; set; }
        public string ZIP { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string ADDRESS_LINES1 { get; set; }
        public string ADDRESS_LINES2 { get; set; }
    
        public virtual WEB_Address WEB_Address1 { get; set; }
        public virtual WEB_Address WEB_Address2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_Customer> WEB_Customer { get; set; }
    }
}
