//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_InvoiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_InvoiceType()
        {
            this.WEB_ItemType = new HashSet<WEB_ItemType>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string ProductName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> FinalModifyDate { get; set; }
        public Nullable<int> ModifyTimeToExpiration { get; set; }
        public Nullable<int> AllowChanges { get; set; }
        public Nullable<int> AllowCancellation { get; set; }
        public Nullable<bool> NotifyOnPayment { get; set; }
        public Nullable<bool> PreviousPaymentRequiredForRefund { get; set; }
    
        public virtual WEB_InvoiceType WEB_InvoiceType1 { get; set; }
        public virtual WEB_InvoiceType WEB_InvoiceType2 { get; set; }
        public virtual WEB_InvoiceType WEB_InvoiceType11 { get; set; }
        public virtual WEB_InvoiceType WEB_InvoiceType3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_ItemType> WEB_ItemType { get; set; }
    }
}
