//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceImport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Invoice_Items
    {
        public int ID { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<int> Set_Number { get; set; }
        public Nullable<int> Item_Type { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<decimal> BOGoodsTax { get; set; }
        public Nullable<decimal> BOServicesTax { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<System.DateTime> Process_Date { get; set; }
        public Nullable<bool> Imported { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<int> Cancel_Set { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public Nullable<bool> Cancel_Imported { get; set; }
        public string Coupon_Code { get; set; }
    
        public virtual WEB_Invoices WEB_Invoices { get; set; }
    }
}
